apiVersion: v1
kind: Pod
metadata:
  name: gpu-check-v2
  namespace: default
spec:
  restartPolicy: Never
  containers:
  - name: cuda-container
    image: nvidia/cuda:12.3.1-base-ubuntu22.04
    command: ["nvidia-smi"]
    resources:
      limits:
        nvidia.com/gpu: 1
    securityContext:
      privileged: false
  nodeSelector:
    kubernetes.io/hostname: minikube
